export const translations = {
    "Sunny": "Солнечно",
    "Clear": "Ясно",
    "Partly cloudy": "Переменная облачность",
    "Cloudy": "Облачно",
    "Overcast": "Пасмурно",
    "Mist": "Туман",
    "Patchy rain possible": "Возможен дождь",
    "Patchy snow possible": "Возможен снег",
    "Patchy sleet possible": "Возможен мокрый снег",
    "Patchy freezing drizzle possible": "Возможен ледяной дождь",
    "Thundery outbreaks possible": "Возможны грозы",
    "Blowing snow": "Метель",
    "Blizzard": "Метель",
    "Fog": "Туман",
    "Freezing fog": "Ледяной туман",
    "Patchy light drizzle": "Местами небольшой моросящий дождь",
    "Light drizzle": "Небольшой моросящий дождь",
    "Freezing drizzle": "Ледяной моросящий дождь",
    "Heavy freezing drizzle": "Сильный ледяной моросящий дождь",
    "Patchy light rain": "Местами небольшой дождь",
    "Light rain": "Небольшой дождь",
    "Moderate rain at times": "Временами умеренный дождь",
    "Moderate rain": "Умеренный дождь",
    "Heavy rain at times": "Временами сильный дождь",
    "Heavy rain": "Сильный дождь",
    "Light freezing rain": "Небольшой ледяной дождь",
    "Moderate or heavy freezing rain": "Умеренный или сильный ледяной дождь",
    "Light sleet": "Небольшой мокрый снег",
    "Moderate or heavy sleet": "Умеренный или сильный мокрый снег",
    "Patchy light snow": "Местами небольшой снег",
    "Light snow": "Небольшой снег",
    "Patchy moderate snow": "Местами умеренный снег",
    "Moderate snow": "Умеренный снег",
    "Patchy heavy snow": "Местами сильный снег",
    "Heavy snow": "Сильный снег",
    "Ice pellets": "Ледяные шарики",
    "Light rain shower": "Небольшой ливневый дождь",
    "Moderate or heavy rain shower": "Умеренный или сильный ливневый дождь",
    "Torrential rain shower": "Ливень",
    "Light sleet showers": "Небольшие ливни мокрого снега",
    "Moderate or heavy sleet showers": "Умеренные или сильные ливни мокрого снега",
    "Light snow showers": "Небольшие снегопады",
    "Moderate or heavy snow showers": "Умеренные или сильные снегопады",
    "Light showers of ice pellets": "Небольшие ливни ледяных шариков",
    "Moderate or heavy showers of ice pellets": "Умеренные или сильные ливни ледяных шариков",
    "Patchy light rain with thunder": "Местами небольшой дождь с грозой",
    "Moderate or heavy rain with thunder": "Умеренный или сильный дождь с грозой",
    "Patchy light snow with thunder": "Местами небольшой снег с грозой",
    "Moderate or heavy snow with thunder": "Умеренный или сильный снег с грозой",
    "Patchy rain nearby": "Местами дождь поблизости"
};


